name: 'CodeClimate'
description: 'GitHub Action that uploads coverage reports for your repository to codeclimate.com'
author: 'Ivan Stasiuk <@brokeyourbike>'
inputs:
  token:
    description: 'Repository upload token - get it from codeclimate.com'
    required: true
  files:
    description: 'Comma-separated list of files to upload'
    required: false
  prefix:
    required: false
    description: 'See https://docs.codeclimate.com/docs/configuring-test-coverage'
  verbose:
    description: 'Specify whether the Code Climate output should be verbose'
    required: false
  version:
    description: 'Specify which version of the Code Climate reporter should be used'
    default: latest
    required: false
  working-directory:
    description: 'Directory in which to execute Code Climate reporter'
    required: false
branding:
  color: 'gray-dark'
  icon: 'umbrella'
runs:
  using: 'node16'
  main: 'dist/index.js'
